version: "2"
services:

    ##########################################
    #      GCC
    ##########################################

    # gcc 9
    build_gcc_9:
        image: ghcr.io/rikorose/gcc-cmake:gcc-9
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build
            && cmake --build build"

    # gcc 10
    build_gcc_10:
        image: ghcr.io/rikorose/gcc-cmake:gcc-10
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    # gcc 11
    build_gcc_11:
        image: ghcr.io/rikorose/gcc-cmake:gcc-11
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    # gcc 12
    build_gcc_12:
        image: ghcr.io/rikorose/gcc-cmake:gcc-12
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    ##########################################
    #      CLANG
    ##########################################

    # clang 6
    build_clang_6:
        image: silkeh/clang:6
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++
            && cmake --build build"

    # clang 7
    build_clang_7:
        image: silkeh/clang:7
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && apt update && upgrade
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++
            && cmake --build build"

    # clang 8
    build_clang_8:
        image: silkeh/clang:8
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++
            && cmake --build build"

    # clang 9
    build_clang_9:
        image: silkeh/clang:9
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    # clang 10
    build_clang_10:
        image: silkeh/clang:10
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    # clang 11
    build_clang_11:
        image: silkeh/clang:11
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    # clang 12
    build_clang_12:
        image: silkeh/clang:12
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    # clang 13
    build_clang_13:
        image: silkeh/clang:13
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"

    # clang 14
    build_clang_14:
        image: silkeh/clang:14
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build
            && rm -rf build
            && cmake -B build -D CMAKE_CXX_compiler=clang++ -D CMAKE_CXX_STANDARD=20 -D CMAKE_CXX_STANDARD_REQUIRED=ON 
            && cmake --build build"